
server:
  port: 8087
spring:
  application:
    name: notification-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rainiq_notification}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:rainiq123}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: rainiq.notifications@gmail.com
    password: ${MAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
              enable: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

jwt:
  secret: ${JWT_SECRET:thisIsAVeryLongSecretKeyForRainIQProjectThatIsAtLeast256BitsLong}
property:
  service:
    url: http://localhost:8082
design:
  service:
    url: http://localhost:8081
internal:
  service:
    token: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJpbnRlcm5hbEByYWluaXEuY29tIiwiaWF0IjoxNzgyNjQzNTYwLCJleHAiOjE4NDU3MTU1NjAsInJvbGUiOiJJTlRFUk5BTF9TRVJWSUNFIn0.AAKbNV5FQVu2pCWV6jiy3-oiJZ51fDgZCi1tGO_KrvfmM2EwCggwjzaPBoQcjwvo
eureka:
  client:
    service-url:
      defaultZone:   ${EUREKA_URI:http://localhost:8761/eureka}
