server:
  port: 8084
spring:
  application:
    name: compliance-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rainiq_compliance}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:rainiq123}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    locations: classpath:db/migration
    enabled: true
  kafka:
    bootstrap-servers:  ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.rainiq.complianceservice.event.DesignSubmittedEvent
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
jwt:
  secret: ${JWT_SECRET:thisIsAVeryLongSecretKeyForRainIQProjectThatIsAtLeast256BitsLong}
property:
  service:
    url: http://localhost:8082
design:
  service:
    url: http://localhost:8081
rainfall:
  service:
    url: http://localhost:8083
internal:
  service:
    token: eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJpbnRlcm5hbEByYWluaXEuY29tIiwiaWF0IjoxNzg2ODEzNDY3LCJleHAiOjE4NDk4ODU0NjcsInJvbGUiOiJJTlRFUk5BTF9TRVJWSUNFIn0.PfU0Lkj7sPBIiqtngBoJhfZKqo2kDi0H7VK6RJ5yaKW6s96BL2YNKH__UqHESsTn
eureka:
  client:
    service-url:
      defaultZone:   ${EUREKA_URI:http://localhost:8761/eureka}
management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: health, prometheus